[package]
name = "mudae-sniper"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenv = "0.15.0"
reqwest = "0.12.22"
serenity_self = {version = "0.13.3", features = ["cache", "collector"]}
tokio = {version = "1.47.1", features = ["full"]}
